# Generated by Django 2.2.27 on 2022-03-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='plans',
            field=models.ManyToManyField(blank=True, related_name='program_plans', to='plans.Plan'),
        ),
    ]
