# Generated by Django 2.2.27 on 2022-03-28 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_userprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='repetition',
            field=models.PositiveIntegerField(blank=True, help_text='How many repetitions of this workout has been performed?', null=True),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='set',
            field=models.PositiveIntegerField(blank=True, help_text='How many sets of this workout has been performed?', null=True),
        ),
    ]
