# Generated by Django 2.2.27 on 2022-04-01 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
        ('programs', '0004_auto_20220328_0745'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='workout',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_progress_workout', to='workouts.Workout'),
        ),
    ]
