# Generated by Django 2.2.27 on 2022-04-04 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_plans', '0004_workoutplan_rest_period'),
        ('programs', '0006_userplan'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='workout_plans',
            field=models.ManyToManyField(blank=True, related_name='program_workout_plans', to='workout_plans.WorkoutPlan'),
        ),
    ]
