# Generated by Django 2.2.27 on 2022-04-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_program_workout_plans'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprogress',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
