# Generated by Django 2.2.26 on 2022-02-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_availableday'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='apointment_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='zoom_link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
