# Generated by Django 2.2.26 on 2022-02-16 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutvideo',
            name='body_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='workoutvideo',
            name='workout_category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
