# Generated by Django 2.2.27 on 2022-03-28 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='days',
            field=models.PositiveIntegerField(blank=True, help_text='Number of days for this plan.', null=True),
        ),
    ]
