# Generated by Django 2.2.27 on 2022-03-25 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='repetitions',
            field=models.PositiveIntegerField(blank=True, help_text='How many repetitions of this workout to be performed?', null=True),
        ),
        migrations.AddField(
            model_name='workoutplan',
            name='sets',
            field=models.PositiveIntegerField(blank=True, help_text='How many sets of this workout to be performed?', null=True),
        ),
    ]
