# Generated by Django 2.2.27 on 2022-03-28 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_plans', '0003_workoutplan_plan_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='rest_period',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
