# Generated by Django 2.2.27 on 2022-04-04 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_plans', '0004_workoutplan_rest_period'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutplan',
            name='order_number',
            field=models.PositiveIntegerField(blank=True, help_text='Order number of the exercise.', null=True),
        ),
    ]
