# Generated by Django 2.2.27 on 2022-04-04 17:40

from django.db import migrations, models
import utils


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workout',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=utils.generate_file_name),
        ),
        migrations.AddField(
            model_name='workout',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
