# Generated by Django 2.2.26 on 2022-01-20 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='fitness_goal',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default='F', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='height_metric',
            field=models.CharField(blank=True, choices=[('CM', 'CMs'), ('FEET', 'Feets')], default='CM', max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='student_campus_residential_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='weight_metric',
            field=models.CharField(blank=True, choices=[('KG', 'KGs'), ('LB', 'LBs')], default='LB', max_length=10, null=True),
        ),
    ]
