# Generated by Django 2.2.26 on 2022-02-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220120_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_trainer',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
