# Generated by Django 2.2.27 on 2022-04-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_userplan'),
        ('gyms', '0002_gym_trial_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gym',
            name='program',
        ),
        migrations.AddField(
            model_name='gym',
            name='program',
            field=models.ManyToManyField(blank=True, null=True, related_name='gym_program', to='programs.Program'),
        ),
    ]
