# Generated by Django 2.2.27 on 2022-04-04 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0003_auto_20220404_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gym',
            name='program',
            field=models.ManyToManyField(blank=True, related_name='gym_program', to='programs.Program'),
        ),
    ]
