# Generated by Django 2.2.27 on 2022-04-04 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gyms', '0004_auto_20220404_1639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gym',
            old_name='trial_code',
            new_name='code',
        ),
    ]
